import {
  ProviderCallError,
  type LlmGenerateRequest,
  type LlmGenerateResponse,
  type LlmProvider,
  type ProviderCapability,
  type SttProvider,
  type SttTranscribeRequest,
  type SttTranscribeResponse,
  type TtsProvider,
  type TtsSynthesizeRequest,
  type TtsSynthesizeResponse,
} from './types';

function extractLastUserMessage(messages: LlmGenerateRequest['messages']): string {
  const found = [...messages].reverse().find((item) => item.role === 'user');
  return found?.content?.trim() ?? '';
}

function buildFallbackJsonReply(lastUserMessage: string): string | null {
  if (lastUserMessage.includes('"accuracy"') && lastUserMessage.includes('"fluency"')) {
    return JSON.stringify({
      accuracy: 78,
      fluency: 74,
      tip: 'Keep a steady rhythm and open the vowels clearly.',
    });
  }

  if (lastUserMessage.includes('JSON array of objects')) {
    return JSON.stringify([
      {
        original: 'Yo soy cansado',
        corrected: 'Estoy cansado',
        type: 'grammar',
        explanation: 'Use estar for temporary states.',
      },
      {
        original: 'Me gusto',
        corrected: 'Me gustó',
        type: 'spelling',
        explanation: 'Past tense needs the accent mark.',
      },
    ]);
  }

  if (lastUserMessage.includes('"continueLearning"') && lastUserMessage.includes('"recommendedCards"')) {
    return JSON.stringify({
      continueLearning: {
        moduleName: 'Fallback Core Path',
        lessonTitle: 'Conversation Loop',
        description: 'Generated by local fallback provider.',
        currentLesson: 3,
        totalLessons: 10,
        progress: 34,
      },
      recommendedCards: [
        {
          id: '1',
          title: 'Listening Sprint',
          description: 'Short listening drill with high-frequency phrases.',
          duration: '7 min',
          level: 'Intermediate',
          type: 'listening',
          icon: 'headphones',
          accentColor: 'violet',
        },
        {
          id: '2',
          title: 'Speaking Shadowing',
          description: 'Repeat and record practical dialogue lines.',
          duration: '8 min',
          level: 'Intermediate',
          type: 'speaking',
          icon: 'mic',
          accentColor: 'blue',
        },
        {
          id: '3',
          title: 'Review Loop',
          description: 'Reinforce weak structures from recent sessions.',
          duration: '6 min',
          level: 'Intermediate',
          type: 'review',
          icon: 'rotate-ccw',
          accentColor: 'amber',
        },
        {
          id: '4',
          title: 'Grammar Checkpoint',
          description: 'Tense consistency and sentence ordering practice.',
          duration: '10 min',
          level: 'Intermediate',
          type: 'grammar',
          icon: 'book-open',
          accentColor: 'indigo',
        },
      ],
      focusAreas: [
        { skill: 'Listening', percentage: 61, color: 'violet' },
        { skill: 'Speaking', percentage: 54, color: 'blue' },
        { skill: 'Vocabulary', percentage: 66, color: 'emerald' },
        { skill: 'Grammar', percentage: 49, color: 'rose' },
      ],
      dailyMission: {
        title: 'Fallback speaking sprint',
        description: 'One speaking set, one review block, one listening pass.',
        progress: 1,
        total: 3,
        xpReward: 60,
      },
    });
  }

  if (lastUserMessage.includes('"learnSession"') && lastUserMessage.includes('"practicePrompt"')) {
    return JSON.stringify({
      learnSession: {
        title: 'New Concept: Daily Greeting',
        concept: 'Use a short, polite greeting that fits context and formality.',
        example: 'Greeting + name + short courtesy phrase.',
        practicePrompt: 'Write a short greeting sentence.',
        answer: 'Sample greeting sentence',
      },
    });
  }

  if (lastUserMessage.includes('"practiceItems"') && lastUserMessage.includes('"type": "mcq|translate|speak"')) {
    return JSON.stringify({
      practiceItems: [
        {
          id: '1',
          type: 'mcq',
          prompt: 'Choose the best opening greeting.',
          answer: 'Option A',
          options: ['Option A', 'Option B', 'Option C', 'Option D'],
        },
        {
          id: '2',
          type: 'translate',
          prompt: 'Translate: "I practice every day."',
          answer: 'Localized translation',
        },
        {
          id: '3',
          type: 'speak',
          prompt: 'Say one short self-introduction line.',
          answer: 'Short self-introduction',
        },
        {
          id: '4',
          type: 'translate',
          prompt: 'Translate: "Thank you for helping me."',
          answer: 'Localized translation',
        },
      ],
    });
  }

  return null;
}

export class LocalFallbackProvider implements LlmProvider, SttProvider, TtsProvider {
  id = 'local-fallback';
  displayName = 'Local Fallback';
  isLocal = true;

  listCapabilities(): ProviderCapability[] {
    return [
      { modality: 'llm', model: 'local-fallback-chat', tags: ['fallback', 'local'] },
      { modality: 'stt', model: 'local-fallback-stt', tags: ['fallback', 'local'] },
      { modality: 'tts', model: 'local-fallback-tts', tags: ['fallback', 'local'] },
    ];
  }

  async complete(request: LlmGenerateRequest): Promise<LlmGenerateResponse> {
    const lastUserMessage = extractLastUserMessage(request.messages);
    const maybeJson = buildFallbackJsonReply(lastUserMessage);
    const text =
      maybeJson ??
      `Fallback response: received "${lastUserMessage.slice(0, 180)}". Continue with the next prompt.`;

    return {
      text,
      model: 'local-fallback-chat',
      providerId: this.id,
    };
  }

  async transcribe(request: SttTranscribeRequest): Promise<SttTranscribeResponse> {
    void request;
    return {
      text: 'Buenos dias, como esta usted',
      model: 'local-fallback-stt',
      providerId: this.id,
    };
  }

  async synthesize(request: TtsSynthesizeRequest): Promise<TtsSynthesizeResponse> {
    void request;
    throw new ProviderCallError({
      providerId: this.id,
      modality: 'tts',
      message: 'Local fallback provider does not synthesize audio blobs.',
      code: 'TTS_NOT_IMPLEMENTED',
      retryable: false,
    });
  }
}
