/**
 * Stroke-order models for Script Practice.
 *
 * Generated by `pnpm seed:script-models` from two open datasets — Make Me a
 * Hanzi for Han characters and KanjiVG for Japanese kana. Do not hand-edit the
 * JSON under `scriptModels/`; change `scripts/characterSets.mjs` and
 * regenerate.
 *
 * Stored in a 1024 grid with y downward and scaled here, so the canvas can
 * change size without the data going stale.
 */
import type { ScriptStrokeModel } from '../types/scriptPractice';
import zhModels from './scriptModels/zh.json';
import jaModels from './scriptModels/ja.json';

/** The square the practice canvas draws in. */
export const SCRIPT_CANVAS_SIZE = 320;

/** The grid the generated data is expressed in. */
const SOURCE_GRID = 1024;

interface GeneratedModel {
  character: string;
  reading?: string;
  meaning?: string;
  source?: string;
  kind?: string;
  strokes: Array<{ index: number; points: Array<{ x: number; y: number; t: number }> }>;
}

export type ScriptCharacterKind = 'hanzi' | 'hiragana' | 'katakana' | 'kanji';

export interface ScriptModelSummary {
  key: string;
  character: string;
  kind: ScriptCharacterKind;
  reading?: string;
  strokeCount: number;
}

const generated: Record<string, GeneratedModel[]> = {
  zh: zhModels as GeneratedModel[],
  ja: jaModels as GeneratedModel[],
};

function modelKey(languageCode: string, character: string): string {
  return `${languageCode}:${character}`;
}

function kindOf(model: GeneratedModel, languageCode: string): ScriptCharacterKind {
  if (model.kind === 'hiragana' || model.kind === 'katakana' || model.kind === 'kanji') {
    return model.kind;
  }
  return languageCode === 'ja' ? 'kanji' : 'hanzi';
}

/**
 * Scaling is memoised per language and size: the Chinese set is several hundred
 * characters, and rescaling all of them on every render of the picker was
 * needless work.
 */
const scaledCache = new Map<string, ScriptStrokeModel[]>();

function scaleModels(languageCode: string, size: number): ScriptStrokeModel[] {
  const cacheKey = `${languageCode}@${size}`;
  const cached = scaledCache.get(cacheKey);
  if (cached) return cached;

  const source = generated[languageCode] ?? [];
  const factor = size / SOURCE_GRID;

  const scaled: ScriptStrokeModel[] = source.map((model) => ({
    key: modelKey(languageCode, model.character),
    character: model.character,
    reading: model.reading,
    meaning: model.meaning,
    strokes: model.strokes.map((stroke) => ({
      index: stroke.index,
      points: stroke.points.map((point) => ({
        x: Math.round(point.x * factor),
        y: Math.round(point.y * factor),
        t: point.t,
      })),
    })),
  }));

  scaledCache.set(cacheKey, scaled);
  return scaled;
}

export function getScriptModels(
  languageCode: string,
  size: number = SCRIPT_CANVAS_SIZE,
): ScriptStrokeModel[] {
  return scaleModels(languageCode, size);
}

/**
 * Looks up one character's model.
 *
 * Returns null when a specific character was asked for and is not in the set.
 * Falling back to the first model instead would score a learner's drawing
 * against a completely different character, and report it as their result.
 */
export function findScriptModel(
  languageCode: string,
  modelKeyOrCharacter?: string,
  size: number = SCRIPT_CANVAS_SIZE,
): ScriptStrokeModel | null {
  const list = scaleModels(languageCode, size);
  if (list.length === 0) return null;
  if (!modelKeyOrCharacter) return list[0];
  return (
    list.find((item) => item.key === modelKeyOrCharacter)
    ?? list.find((item) => item.character === modelKeyOrCharacter)
    ?? null
  );
}

/** The character a session opens on when none was requested or the request missed. */
export function defaultScriptModel(
  languageCode: string,
  requested?: string,
  size: number = SCRIPT_CANVAS_SIZE,
): ScriptStrokeModel | null {
  return findScriptModel(languageCode, requested, size) ?? findScriptModel(languageCode, undefined, size);
}

/**
 * Lightweight index for pickers and search, so a browsing UI does not have to
 * hold every stroke point of several hundred characters.
 */
export function listScriptCharacters(languageCode: string): ScriptModelSummary[] {
  const source = generated[languageCode] ?? [];
  return source.map((model) => ({
    key: modelKey(languageCode, model.character),
    character: model.character,
    kind: kindOf(model, languageCode),
    reading: model.reading,
    strokeCount: model.strokes.length,
  }));
}

export function scriptLanguageIsSupported(languageCode: string): boolean {
  return (generated[languageCode]?.length ?? 0) > 0;
}
